# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: format
        name: Elixir/Format
        language: system
        entry: mix format
        files: \.(ex|exs)
        pass_filenames: false

      - id: credo
        name: Elixir/Credo
        language: system
        entry: mix credo --strict
        files: \.(ex|exs)
        pass_filenames: false

      - id: test
        name: Elixir/Test
        language: system
        entry: mix test
        files: \.(ex|exs)
        pass_filenames: false

      - id: compile
        name: Elixir/Compile
        language: system
        entry: mix compile --force --warnings-as-errors
        files: \.(ex|exs)
        pass_filenames: false